### ISSUE TITLE
JSON Handling Guide Nonfunctional

### ISSUE THREAD

**Issue by milescrawford** [scalatra/scalatra-website#113]
In the JSON handling guide here: http://www.scalatra.org/2.4/guides/formats/json.html

The "Receiving JSON" example is erroneous and does not compile.

Instead of:
`request.body.extract[Person]`
it should read:
`parsedBody.extract[Person]`

**Comment by futurechimp** [comment]
Should be fixed by 48036d9dd66cd7b5ed52d247a681f31b318b0904. The site has rebuilt and the fix is available.
