### ISSUE TITLE
version 2.5

### ISSUE THREAD

**Issue by seratch** [scalatra/scalatra-website#126]
Should we create the 2.5 branch? or should we change the policy on branches?

**Comment by seratch** [comment]
I'd like to stop creating 2.x branch every time when we start new minor version. Is it reasonable to just use 2.4 from now on or using another branch? I'm not sure how the website is built in detail.

**Comment by seratch** [comment]
Ah, I should discuss here: https://gitter.im/scalatra/scalatra

**Comment by takezoe** [comment]
Scalatra 2.5 docs has been published with the hugo branch.
