### ISSUE TITLE
Update Scalate documentation

### ISSUE THREAD

**Issue by takezoe** [scalatra/scalatra-website#160]
https://github.com/scalatra/scalatra/issues/728

**Comment by magnolia-k** [comment]
update to twirl
https://github.com/scalatra/scalatra-website/pull/161

**Comment by nudemeth** [comment]
Hi,

I'm a beginner for contribution. I've updated Scalate documentation [#162](https://github.com/scalatra/scalatra-website/pull/162). Any suggestions, please let me know.

**Comment by takezoe** [comment]
@nudemeth Thanks! Is it possible to update the coming 2.6 document in `scalatra-2.6` branch as well?

**Comment by nudemeth** [comment]
Done on branch `scalatra-2.6`. [#164](https://github.com/scalatra/scalatra-website/pull/164)

**Comment by takezoe** [comment]
@nudemeth Merged. Great thanks!
