### ISSUE TITLE
Can not resolve www.scalatra.org

### ISSUE THREAD

**Issue by exoego** [scalatra/scalatra-website#190]
The description of this repository contains URL `www.scalatra.org` which seems unable to be resolved.
![image](https://user-images.githubusercontent.com/127635/57200751-60d29080-6fca-11e9-8b5c-427a477c109e.png)

**Comment by magnolia-k** [comment]
As you point out, the changes when we recreate the official site are not reflected

**Comment by magnolia-k** [comment]
@takezoe please fix site url

**Comment by takezoe** [comment]
Done.
