### ISSUE TITLE
https://scalatra.org has issues about domain certification

### ISSUE THREAD

**Issue by exoego** [scalatra/scalatra-website#191]
`https` schema URL is written in README.
However, it seems that https://scalatra.org has an issue about domain certification.

![image](https://user-images.githubusercontent.com/127635/57201112-47801300-6fcf-11e9-9b7b-04037e93e25c.png)
(Sorry, screenshot was taken in Japanese language)

**Comment by rossabaker** [comment]
I don't remember setting up https on this.  I'm not so involved on the project anymore, but would be happy to transfer the domain to help get it set up properly.

**Comment by counter2015** [comment]
![image](https://user-images.githubusercontent.com/13608862/68202061-eaa4fa00-fffd-11e9-9cf6-1fb78eec65bb.png)

This was what I see from Firefox.

**Comment by treaz** [comment]
@rossabaker I can pick this one up if you give me more info

**Comment by rossabaker** [comment]
I think the CNAME needs to be set to scalatra.org, but GitHub says it's already in use.  Does anybody know which repo that might be?

I'd still be happy to transfer the domain to anyone more actively involved.

**Comment by rossabaker** [comment]
Looks like https://github.com/scalatra/scalatra-docbuild/settings.  Which one of those projects actually hosts the site now?  I think that one needs the CNAME.

**Comment by treaz** [comment]
This is actually dead simple to do, but only an admin can do it @magnolia-k @takezoe 
go to https://github.com/scalatra/scalatra-docbuild -> settings -> GitHub Pages -> enforce https

Reference: 
https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https

**Comment by rossabaker** [comment]
That option was disabled, because GitHub changed their IP addresses and no corresponding change was made to the DNS.  I just added the proper A records for a bare domain, and CNAME for www.  You should be able to check that box within 24 hours, but it's still generating the cert now.

The domain expires in June, and I'm ready to start a transfer if somebody is ready to claim it.

**Comment by treaz** [comment]
@rossabaker scalatra.org is now running on HTTPS. Thank you for your help. Regarding the domain transfer... I would say that maybe you need to talk to the people in charge directly ;)
