### ISSUE TITLE
Create 2.7 guides

### ISSUE THREAD

**Issue by treaz** [scalatra/scalatra-website#194]
I've been working with 2.7.0-RC1 making a demo project that demoes all the features of scalatra. 
I'd like to start a branch for 2.7.0 in which I can update a couple of things.
What's the best way to do that?

**Comment by takezoe** [comment]
As you may know, guides for each version are available under this directory: 
https://github.com/scalatra/scalatra-website/tree/master/content/guides

We simply copy the contents of the previous version and create update them when we need to create docs for a new version.

**Comment by treaz** [comment]
Ok, I'll create a copy as soon as you approve&merge https://github.com/scalatra/scalatra-website/pull/195
