### ISSUE TITLE
broken link on 2.6 riak doc page

### ISSUE THREAD

**Issue by treaz** [scalatra/scalatra-website#199]
See riak-example for a minimal and standalone project containing the example in this guide. 
https://github.com/scalatra/scalatra-website-examples/tree/master/2.6/persistence/riak-example does not exist

**Comment by treaz** [comment]
@takezoe @magnolia-k I've started work on an example for Riak and scalatra 2.7. However, I notice that the official Riak java client (the one used in the [doc](http://scalatra.org/guides/2.7/persistence/riak.html) page) hasn't been updated since 2016. And the docs don't match the source code anymore (directory structure has changed and the imports don't work as specified). The other clients haven't been updated for 8-9 years.

In my world, this means discontinued projects. As I result, I would suggest we drop entirely the documentation page for Riak. What do you think about this?

**Comment by magnolia-k** [comment]
@treaz 

I don't think it is necessary to update the code for Riak as a sample code from the maintenance status of Riak's Java Client.

(Because Scalatra doesn't have Riak-specific support function in the first place)

**Comment by treaz** [comment]
@magnolia-k shall we just remove [the riak doc page](http://scalatra.org/guides/2.7/persistence/riak.html) then?

**Comment by takezoe** [comment]
Also, I think there is no high demand for Riak due to the current Riak situation.
I think we can just remove Riak doc.

**Comment by treaz** [comment]
I have made a commit on branch 2.7 in which I removed riak docs starting from version 2.7. I'm closing this issue

**Comment by takezoe** [comment]
Thanks!
