### ISSUE TITLE
broken link on 2.6 mongo doc page

### ISSUE THREAD

**Issue by treaz** [scalatra/scalatra-website#200]
See scalatra-casbah-example for a minimal and standalone project containing the example in this guide.
https://github.com/scalatra/scalatra-website-examples/tree/master/2.6/persistence/scalatra-casbah-example does not exist

**Comment by treaz** [comment]
I've created the mongo example project. The thing is that casbah is EOL, and now we're using mongo-scala-driver and the mongo document needs to be updated to reflect the code in the example

**Comment by treaz** [comment]
fixed in https://github.com/scalatra/scalatra-website/pull/206

**Comment by magnolia-k** [comment]
merged!
