### ISSUE TITLE
issues with Github pages ?

### ISSUE THREAD

**Issue by Thomas-Coville** [scalatra/scalatra-website#203]
Hi !

I am not able to reach the site since yesterday, I'm surprised that i don't see any one else complaining about it... Am I the only one experiencing this ?
![image](https://user-images.githubusercontent.com/5576692/74204641-04c82700-4c42-11ea-91be-f22dbcf4990a.png)

**Comment by treaz** [comment]
confirmed

**Comment by treaz** [comment]
something went wrong in the build process of the docs; suggested workaround until then, run the docs locally (see readme)

**Comment by treaz** [comment]
fix is in https://github.com/scalatra/scalatra-website/pull/205. Waiting for merge

**Comment by treaz** [comment]
@Thomas-Coville it's fixed now
